all:
	gcc main.c hashTable.c -o winner.exe

main:
	gcc -c main.c hashTable.c

runtest:
	gcc main.c hashTable.c -o winner.exe
	./testmain.tcl ./winner.exe

run:
	gcc main.c hashTable.c -o winner.exe
	./winner.exe